distance/urls.py
'''distance/urls.py - Consists of non-administrative urls (not related to log
in, log out, passwords, or the admin site)'''
from django.conf.urls import url

from . import views
# for favicon and menu, need RedirectView
from django.views.generic.base import RedirectView

app_name = 'distance'
urlpatterns = [
    url(r'^home/$', views.index, name='index'),

    url(r'^signup/$', views.signup, name='signup'),

    # Adding friends
    url(r'^search_friends/$', views.search_friends, name='search_friends'),
    url(r'^add_friend/$', views.add_friend, name='add_friend'),

    # Viewing messages
    url(r'^messages/$', views.view_messages, name='view_messages'),

    # Accepting friend request
    url(r'^accept/$', views.accept, name='accept'),

    # View list of friends
    url(r'^friends/$', views.friends, name='friends'),

    # View homepage with a given friend
    url(r'^friends/(?P<friend_id>[0-9]+)/$', views.friend_view, name='friend_view'),

    # Add images to a given friend's homepage background
    url(r'^friends/(?P<friend_id>[0-9]+)/add_images/$', views.add_images, name='add_images'),
    url(r'^friends/(?P<friend_id>[0-9]+)/image_confirm/$', views.image_confirm, name='image_confirm'),

    # Send a message
    url(r'^send_msg/$', views.send_msg, name="send_msg"),
    url(r'^friends/(?P<friend_id>[0-9]+)/send_msg/$', views.send_msg, name='send_msg_f'),

    # Delete an image from a given friend's homepage background
    url(r'^friends/(?P<friend_id>[0-9]+)/del_img/$', views.del_img, name='del_img'),

    # Delete a friend.
    url(r'^del_friend/$', views.del_friend, name='del_friend'),

    # Settings
    url(r'^settings_view/$', views.settings_view, name='settings_view'),
    url(r'^settings_set/$', views.settings_set, name='settings_set'),

    # Images on the site
    url(r'^background\.jpg', RedirectView.as_view(url='static/distance/foto_no_exif.jpg'), name='background'),
    url(r'^compose\.png', RedirectView.as_view(url='static/distance/oie_transparent.png'), name='compose'),
    url(r'^logo\.png', RedirectView.as_view(url='static/distance/Logo.png'), name='logo'),
    url(r'^favicon\.png', RedirectView.as_view(url='static/distance/favicon.png'), name='favicon'),
    url(r'^favicon_apple\.png', RedirectView.as_view(url='static/distance/favicon_apple.png'), name='favicon_apple'),
    url(r'^menu\.png', RedirectView.as_view(url='static/distance/Menu.png'), name='menu'),
]

mysite/urls.py
""" hereandthere url configuration for administrative urls (having to do with
admin site or users/passwords
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('distance.urls', namespace="distance")),
    url(r'^admin/', admin.site.urls),

    # log in, log out
    url(r'^$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    # password reset urls
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

distance/models.py
'''models.py - Creates the models User, Message, and Image.'''
from django.db import models

from django.contrib.auth.models import AbstractUser
import pytz

from django.conf import settings

class User(AbstractUser):
    '''A User has a timezone, connections (users that they are friends with),
    latitude, longitude, temperature unit, city, and country, on top of the
    attributes username, email, and password in AbstractUser.'''
    timezones = pytz.all_timezones
    tz_tuple_list = []
    for tz in timezones:
        tz_tuple_list.append((tz, tz))
    timezone = models.CharField(max_length=100, choices=tz_tuple_list)
    connections = models.ManyToManyField(settings.AUTH_USER_MODEL, null=True, blank=True)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    unit_list = [
        ('K', 'Kelvin'),
        ('C', 'Celsius'),
        ('F', 'Fahrenheit'),
    ]
    temp_unit = models.CharField(max_length=100, choices=unit_list, default='K')
    city = models.CharField(max_length=100, default="Chicago")
    country = models.CharField(max_length=100, default="United States of America")

class Message(models.Model):
    '''A Message has a sender, a receiver, content, a created_at DateTimeField,
    and a message type (either friend request or normal message).'''
    sender = models.ForeignKey(User, related_name="sender")
    receiver = models.ForeignKey(User, related_name="receiver")
    msg_content = models.TextField()
    created_at = models.DateTimeField()
    FRIEND_REQUEST = 'FR'
    NORMAL_MESSAGE = 'NM'
    msg_type_list = [
        ('FR', 'Friend Request'),
        ('NM', 'Normal Message'),
    ]
    msg_type = models.CharField(max_length=100, choices = msg_type_list, default=NORMAL_MESSAGE)
    read = models.BooleanField(default=False)

class Image(models.Model):
    '''An Image has two users that have the Image as one of their background
    images as well as the url to the image.'''
    user1 = models.ForeignKey(User, related_name="user1")
    user2 = models.ForeignKey(User, related_name="user2")
    users = [user1, user2]
    image_url = models.URLField()

distance/forms.py
'''forms.py - Creates the SignUpForm and SettingsForm classes so users can
sign up and change their settings.'''
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
import pytz

class SignUpForm(UserCreationForm):
    '''SignUpForm consists of a timezone (choice field between all timezones
    listed in pytz, latitude (float field), and longitude (float field).
    It then creates a User with a username, email, password, timezone, and
    latitude and longitude.'''
    timezones = pytz.all_timezones
    tz_tuple_list = []
    for tz in timezones:
        tz_tuple_list.append((tz, tz))
    timezone = forms.ChoiceField(choices=tz_tuple_list, help_text='Required. Choose your timezone.')
    lat = forms.FloatField(max_value=90, min_value=-90, help_text='Required. Allow location services or input your latitude.', label='Latitude')
    lng = forms.FloatField(max_value=180, min_value=-180, help_text='Required. Allow location services or input your longitude.', label='Longitude')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'timezone','lat', 'lng')

class SettingsForm(forms.Form):
    '''SettingsForm enables a user to change their settings. They can change
    their timezone, latitude, longitude, city, country, or temperature unit.'''
    timezones = pytz.all_timezones
    tz_tuple_list = []
    for tz in timezones:
        tz_tuple_list.append((tz, tz))
    timezone = forms.ChoiceField(choices=tz_tuple_list, help_text='Change your timezone.')
    lat = forms.FloatField(max_value=90, min_value=-90, help_text='Change your latitude.', label='Latitude')
    lng = forms.FloatField(max_value=180, min_value=-180, help_text='Change your longitude.', label='Longitude')
    city = forms.CharField(help_text='Change your city.')
    country = forms.CharField(help_text=' Change your city.')
    unit_list = [
        ('K', 'Kelvin'),
        ('C', 'Celsius'),
        ('F', 'Fahrenheit'),
    ]
    temp_unit = forms.ChoiceField(choices=unit_list, help_text='Change your temperature unit.', label='Temperature Unit')

    class Meta:
        model = User
        fields = ('timezone', 'lat', 'lng', 'temp_unit', 'city', 'country')

distance/views.py
'''views.py - Contains the various views for the site.'''

from django.contrib.auth import login, authenticate
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.conf import settings

from django.db.models import Q

from .forms import SignUpForm, SettingsForm
from .models import User, Message, Image

import datetime
import pytz

from pyowm import OWM

from geopy.geocoders import Nominatim



def index(request):
    '''Displays the home page.'''
    if request.user.is_authenticated:
        friends_list = request.user.connections.all()
        num_msgs = Message.objects.filter(receiver=request.user, read=False).count()
        return render(request, 'distance/index.html', {'friends_list': friends_list, 'num_msgs': num_msgs})
    return HttpResponseRedirect(reverse('login'))

def signup(request):
    '''Signs up a user and locates their city and country based on their
    inputted latitude and longitude (users can always change it if it's incorrect).'''
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                # geopy uses an API that either declares a city name by
                # village, city, suburb, hamlet, or town based on the city
                # size. So we must try them all.
                try:
                    geolocator = Nominatim()
                    lat_lng = str(user.lat) + ', ' + str(user.lng)
                    location = geolocator.reverse(lat_lng)
                    user.city = location.raw['address']['village']
                except KeyError:
                    try:
                        user.city = location.raw['address']['city']
                    except KeyError:
                        try:
                            user.city = location.raw['address']['suburb']
                        except KeyError:
                            try:
                                user.city = location.raw['address']['hamlet']
                            except KeyError:
                                try:
                                    user.city = location.raw['address']['town']
                                except KeyError:
                                    user.city = 'Not Found'
                try:
                    user.country = location.raw['address']['country']
                except KeyError:
                    user.country = 'Not Found'
                user.save()
                return HttpResponseRedirect(reverse('distance:index'))
        else:
            form = SignUpForm()
        return render(request, 'registration/signup.html', {'form': form})
    messages.add_message(request, messages.INFO, 'You are already logged in. You must log out to create a new user.')
    return HttpResponseRedirect(reverse('distance:index'))

def search_friends(request):
    '''Searches for Users based on the username searched so that the user can
    add as a friend.'''
    if request.user.is_authenticated:
        if request.method == 'GET':
            search = request.GET.get('search_friends')
            # If that username exists
            if User.objects.filter(username=search).count() > 0:
                # Prevent the user from friending theirself
                if User.objects.filter(username=search)[0] != request.user:
                    # Check if they're already friends
                    if User.objects.filter(username=search)[0] in request.user.connections.all():
                        already_friends = True
                    else:
                        already_friends = False
                    # Check if the user has already sent the receiver a friend
                    # request.
                    if Message.objects.filter(sender=request.user,
                        receiver=User.objects.filter(username=search)[0],
                        msg_type=Message.FRIEND_REQUEST).count() > 0:
                        pending = True
                    else:
                        pending = False
                    friends_list = request.user.connections.all()
                    num_msgs = Message.objects.filter(receiver=request.user, read=False).count()
                    context = {
                        'search': search,
                        'already_friends': already_friends,
                        'pending': pending,
                        'friends_list': friends_list,
                        'num_msgs': num_msgs,
                    }
                    return render(request, 'distance/search_results.html', context)
                else:
                    messages.add_message(request, messages.INFO, 'That\'s your username!')
            else:
                messages.add_message(request, messages.INFO, 'That username does not exist.')
    else:
        messages.add_message(request, messages.INFO, 'You are not logged in.')
    return HttpResponseRedirect(reverse('distance:index'))

def add_friend(request):
    '''Sends the receiver a Friend Request message.'''
    if request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('friend_result')
            user = User.objects.filter(username=username)[0]
            msg = request.user.username + ' has sent you a friend request.'
            dt = datetime.datetime.now()
            friend_request = Message(sender=request.user, receiver=user, msg_content=msg, created_at=dt, msg_type=Message.FRIEND_REQUEST)
            friend_request.save()
            messages.add_message(request, messages.INFO, 'You have sent ' + username + ' a friend request.')
    else:
        messages.add_message(request, messages.INFO, 'You are not logged in.')
    return HttpResponseRedirect(reverse('distance:index'))

def view_messages(request):
    '''Gets all the messages that the user is the receiver of.'''
    if request.user.is_authenticated:
        msg_list = Message.objects.filter(receiver=request.user)
        friends_list = request.user.connections.all()
        for msg in msg_list:
            msg.read = True
            msg.save()
        num_msgs = 0
        return render(request, 'distance/messages.html', {'msg_list': msg_list, 'friends_list': friends_list, 'num_msgs': num_msgs})
    else:
        messages.add_message(request, messages.INFO, 'You are not logged in.')
    return HttpResponseRedirect(reverse('distance:index'))

def accept(request):
    '''Accepts a friend request and makes the two users friends.'''
    if request.user.is_authenticated:
        if request.method == 'POST':
            for msg in Message.objects.filter(receiver=request.user):
                if request.POST.get(str(msg.id)) == 'Accept':
                    # add friend request sender to this user's friends
                    request.user.connections.add(msg.sender)
                    # add this user to friend request sender's friends
                    msg.sender.connections.add(request.user)
                    # save both
                    request.user.save()
                    msg.sender.save()
                    messages.add_message(request, messages.INFO, msg.sender.username + ' has been added as a friend.')
                    msg.delete()
                    return HttpResponseRedirect(reverse('distance:view_messages'))
                # delete message (reject friend request)
                elif request.POST.get(str(msg.id) + 'X') == 'X':
                    msg.delete()
                    return HttpResponseRedirect(reverse('distance:view_messages'))
    else:
        messages.add_message(request, messages.INFO, 'You are not logged in.')
    return HttpResponseRedirect(reverse('distance:index'))

def friends(request):
    '''Displays list of friends.'''
    if request.user.is_authenticated:
        friends_list = request.user.connections.all()
        num_msgs = Message.objects.filter(receiver=request.user, read=False).count()
        return render(request, 'distance/friends.html', {'friends_list': friends_list, 'num_msgs': num_msgs})
    else:
        messages.add_message(request, messages.INFO, 'You are not logged in.')
    return HttpResponseRedirect(reverse('distance:index'))

def friend_view(request, **kwargs):
    '''Displays homepage for a given friend.'''
    if request.user.is_authenticated:
        if 'friend_id' in kwargs:
            friend_id = kwargs['friend_id']
            # check to make sure that the user is actually friends with this user
            # (because otherwise they could put arbitrary
            # numbers at the end of the url to see other user pages).
            if request.user.connections.filter(id=friend_id).count() > 0:
                # get offsets for clocks
                friend = request.user.connections.filter(id=friend_id)[0]

                # get request.user's utc offset
                utc_offset1 = datetime.datetime.now(pytz.timezone(request.user.timezone)).strftime('%z')
                hr_offset1 = int(utc_offset1[:3])
                # check if utc offset is positive or negative
                if utc_offset1[:1] == '+':
                    min_offset1 = int(utc_offset1[3:])
                else:
                    min_offset1 = -1 * int(utc_offset1[3:])

                # get friend's utc offset
                utc_offset2 = datetime.datetime.now(pytz.timezone(friend.timezone)).strftime('%z')
                hr_offset2 = int(utc_offset2[:3])
                if utc_offset2[:1] == '+':
                    min_offset2 = int(utc_offset2[3:])
                else:
                    min_offset2 = -1 * int(utc_offset2[3:])

distance/templates/distance/base.html
<!--Setup-->
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Kanit:200" rel="stylesheet" type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'distance/style.css' %}" />
<head>
    <link rel="icon" href="{% url 'distance:favicon' %}" type="image/png">
    <link rel="apple-touch-icon" href="{% url 'distance:favicon_apple' %}" type="image/png">
</head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<img src={% url "distance:logo" %} alt="" id="logo">
<!--Script to show the information text on click-->
<script>
    function showInfoText() {
        var infoText = document.getElementById('info-text');
        if (infoText.style.display == "block")
        {
            infoText.style.display = "none";
        }
        else
        {
            infoText.style.display = "block";
        }
    }
</script>
<div id="info" onClick="showInfoText()">
    <div id="info-i" class="button small-btn">i</div>
    <div id="info-text" class="button">
        <p>
            Welcome to Here and There! You can friend your distant loved ones,
            and make a homepage together where you can view your local times,
            local weather, locations, send messages and link to background images
            of you two for a slideshow!
        </p>
        <p>
            Created by Erica Diaz. If you have any questions, email
            hereandtherequestions@gmail.com.
        </p>
        <p>
            Special thanks to pyowm (Python wrapper for OpenWeatherMap API)!
        </p>
    </div>
</div>
<!--Menu-->
{% if user.is_authenticated %}
    <img src="{% url 'distance:menu' %}" type="image/png" class="menu" id="menu">
    <a href={% url 'distance:index' %} class="button menu-btn" id="home">HOME</a>
    <a href={% url 'distance:view_messages' %} class="button menu-btn">MESSAGES ({{ num_msgs }})</a>
    <div class="dropdown">
        <a href={% url 'distance:friends' %} class="button dropbtn menu-btn">FRIENDS</a>
        <div class="dropdown-content">
            {% for friend in friends_list %}
                <a href="{% url 'distance:friend_view' friend.id %}" class="button drop-user menu-btn">{{ friend.username }}</a>
            {% endfor %}
        </div>
    </div>
    <a href={% url 'distance:settings_view' %} class="button menu-btn">SETTINGS</a>
    <a href={% url 'logout' %} class="button menu-btn">LOG OUT</a>
    {% block more_links %}
    {% endblock %}
    <script>
        var menu = document.getElementById("menu");
        var menuBtns = document.getElementsByClassName("menu-btn");
        var home = document.getElementById("home");
        menu.onclick = function() {
            if (home.style.display != "block")
            {
                // show buttons
                for (var i = 0; i < menuBtns.length; i++)
                {
                    menuBtns[i].style.display = "block";
                }
                // rotate menu icon
                menu.style.transform = "rotate(90deg)";
                menu.style.transition = "all .12s";
            }
            else
            {
                //hide buttons
                for (var i = 0; i < menuBtns.length; i++)
                {
                    menuBtns[i].style.display = "none";
                }
                //rotate menu icon back
                menu.style.transform = "rotate(0deg)";
                menu.style.transition = "all .12s";
            }
        }
    </script>
{% endif %}
<!--Messages-->
{% if messages %}
    <div>
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<!--Background image-->
{% block images %}
<img src={% url "distance:background" %} style="width:100%" alt="" class="background">
{% endblock %}

{% block content %}
{% endblock %}

distance/templates/distance/friend_view.html
{% extends 'distance/base.html' %}
{% block more_links %}
<!--Script to show textbox2-->
<script>
    function ShowTextbox()
    {
        var textbox = document.getElementById("textbox2");
        if (textbox.style.display == "inline")
        {
            textbox.style.display = "none";
        }
        else
        {
            textbox.style.display = "inline";
        }
    }
</script>
<!--Enable user to add and delete images from the friend view page-->
<div id="del_images">
    <div class="button" id="img-desktop" onclick="ShowTextbox()">IMAGES</div>
    <div id="textbox2">
        <div id="image-scroll">
            {% for img in images %}
                <form method="post" action={% url "distance:del_img" friend.id %} class="white-background small">{% csrf_token %}
                    <div class="img-cell">
                        <img src="{{ img }}" alt="" class="img-preview">
                        <input type="submit" value="X" class="button small-X top-left" name="{{ img }}">
                    </div>
                </form>
            {% endfor %}
        </div>
        <div id="add-image">
            <form method="POST" action={% url 'distance:image_confirm' friend.id %} class="white-background" id="add_images">{% csrf_token %}
                <input type="url" name="image_url" class="textbox" required id="image_url">
                <input type="submit" value="SUBMIT" class="button small-btn">
            </form>
        </div>
    </div>
</div>
<a href="{% url 'distance:add_images' friend.id %}" class="button menu-btn" id="img-mobile">IMAGES</a>
{% endblock %}
{% block content %}
<!--Friend View page-->
<head>
    <title>
        {{ friend.username }}
    </title>
</head>

<body onload="startTime()">
<!--Script to start clocks on site-->
<script>
function startTime() {
    var today1 = new Date();
    var today2 = new Date();
    var h = today1.getUTCHours();
    var m = today1.getUTCMinutes();
    var s = today1.getUTCSeconds();
    today1.setHours(h + {{ hr_offset1 }});
    today1.setMinutes(m + {{ min_offset1 }});
    today2.setHours(h + {{ hr_offset2 }});
    today2.setMinutes(m + {{ min_offset2 }});

    var h1 = today1.getHours();
    var m1 = today1.getMinutes();

    var h2 = today2.getHours();
    var m2 = today2.getMinutes();

    var s = today1.getSeconds();

    h1 = checkTime(h1);
    m1 = checkTime(m1);

    h2 = checkTime(h2);
    m2 = checkTime(m2);
    s = checkTime(s);

    document.getElementById('date1').innerHTML =
    today1.toDateString();
    document.getElementById('date2').innerHTML =
    today2.toDateString();

    document.getElementById('clock1').innerHTML =
    h1 + ":" + m1 + ":" + s;
    document.getElementById('clock2').innerHTML =
    h2 + ":" + m2 + ":" + s;
    var t = setTimeout(startTime, 500);
}
function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
</script>

<!--Main content, contains user1, user2, messaging, and background images-->
<div class="slideshow-container">
    <div id="user1">
        <div class="underline">{{ user.username }}</div>
        <div>{{ city1 }}, {{ country1 }}</div>
        <div id="date1"></div>
        <div id="clock1"></div>
        <div id="temp1">{{ temp1 }} {{ status1 }}</div>
    </div>
    <div id="right-side">
        <div id="user2">
            <div class="underline">{{ friend.username }}</div>
            <div>{{ city2 }}, {{ country2 }}</div>
            <div id="date2"></div>
            <div id="clock2"></div>
            <div id="temp2">{{ temp2 }} {{ status2 }}</div>
        </div>
        <div class="messaging">
            <form method="post" action={% url "distance:send_msg_f" friend.id %} class="white-background small">{% csrf_token %}
                <div class="msgs_friend">
                    <div class="content">
                        {% for msg in msg_list %}

                            <div class="underline">
                                {{ msg.sender }}:
                                <div id="created_at">
                                    {{ msg.created_at }}
                                </div>
                            </div>
                            <input type="submit" value="X" class="button small-X" name="{{ msg.id }}FX">
                            <div class="wrap">{{ msg.msg_content }}</div>

                        {% endfor %}
                    </div>
                </div>
                <div class="reply">
                    <textarea placeholder="Enter message here..." name="msg" id="msg"></textarea><br>
                    <div class="text-right">
                        <input type="submit" value="Send" class="button" name="{{ msg.id }}FR">
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% if images %}
        {% block images %}
            {% for image in images %}
                <div class="mySlides fade">
                    <img src={{ image }} style="width:100%" alt="" class="background">
                </div>
            {% endfor %}
        {% endblock %}
    {% else %}
        <img src={% url "distance:background" %} style="width:100%" alt="" class="background">
    {% endif %}
</div>
<!--Script to display image slideshow-->
{% if images %}
    <script>
        var slideIndex = 0;
        showSlides();

        function showSlides() {
            var i;
            var slides = document.getElementsByClassName("mySlides");

            for (i = 0; i < slides.length; i++)
            {
               slides[i].style.display = "none";
            }
            slideIndex++;
            if (slideIndex> slides.length)
            {
                slideIndex = 1
            }
            slides[slideIndex-1].style.display = "block";
            setTimeout(showSlides, 5000); // Change image every 5 seconds
        }
    </script>
{% endif %}


</body>
{% endblock %}

distance/templates/distance/friends.html
{% extends 'distance/base.html' %}
{% block content %}
<!--Friends page-->
    <head>
        <title>
            Friends
        </title>
    </head>
    <h3>Friends:</h3>
    <!--Enable user to delete friends-->
    {% for friend in friends_list %}
        <form method="post" action={% url 'distance:del_friend' %}>{% csrf_token %}
            <input type="submit" value="X" class="button small-btn" name="{{ friend.id }}">
            <a href="{% url 'distance:friend_view' friend.id %}" class="button small-btn div-inline">{{ friend.username }}</a></li>
        </form>
    {% endfor %}
{% endblock %}

distance/templates/distance/messages.html
{% extends 'distance/base.html' %}

{% block content %}
<!--Messages page-->
    <head>
        <title>
            Messages
        </title>
    </head>
    <script>
        // Show compose textbox
        function ShowTextbox()
        {
            var textbox = document.getElementById("textbox");
            if (textbox.style.display == "block")
            {
                textbox.style.display = "none";
            }
            else
            {
                textbox.style.display = "block";
            }
        }
        // Show reply textbox
        function ShowTextbox2(receiver)
        {
            var textbox = document.getElementById("textbox");
            if (textbox.style.display == "block")
            {
                textbox.style.display = "none";
            }
            else
            {
                textbox.style.display = "block";
                document.getElementById("receiver").value = receiver;
            }
        }
    </script>
    <h3>Messages:</h3>
    <div onclick="ShowTextbox()"><img src={% url 'distance:compose' %} alt="" class="right-align white-background" id="compose"></div>
    <div id="textbox">
        <form method="POST" action={% url "distance:send_msg" %} class="white-background right-align"> {% csrf_token %}
            <input type="text" name="receiver" required placeholder="To:" id="receiver"><br>
            <textarea required placeholder="Enter message here..." name="msg" id="msg"></textarea><br>
            <input type="submit" value= "Send" class="button small-btn right-align">
        </form>
    </div>
    <!--Display messages. If it's a friend request, then have two options: Accept and-->
    <!--X. If it's a normal message, then have two options: Reply and X.-->
    {% if msg_list %}
        <div class="signup msgs">
            {% for msg in msg_list %}
                {% if msg.msg_type == "FR" %}
                    <form action={% url "distance:accept" %} method="post" class="white-background">{% csrf_token %}
                        <div class="underline">{{ msg.sender }}: </div>
                        <div class="indented">
                            {{ msg.msg_content }}
                            <div class="text-right">
                                <input type="submit" value="Accept" class="button" name={{ msg.id }}>
                                <input type="submit" value="X" class="button" name="{{ msg.id }}X">
                            </div>
                        </div>
                    </form>
                {% else %}
                    <form method="post" action={% url "distance:accept" %} class="white-background">{% csrf_token %}
                        <div class="underline">{{ msg.sender }}: </div>
                        <div class="indented">
                            {{ msg.msg_content }}
                            <div class="text-right">
                                <div class="button div-inline" id={{ msg.id }} onclick="ShowTextbox2(&quot;{{ msg.sender }}&quot;)">Reply</div>
                                <input type="submit" value="X" class="button" name="{{ msg.id }}X">
                            </div>
                        </div>
                    </form>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}